### PR TITLE
 Use explicit class references for ComponentUI defaults

### PR DESCRIPTION
**Pull request by michaelbull**
The dynamic nature of looking up class names with hardcoded strings makes it hard for tools such as proguard to obfuscate and optimize away theses classes. As it stands, the entirety of the radiance library can be safely ran through proguard - apart from the class names listed below.

As such, anyone wanting to obfuscate their product with proguard that uses substance must add the following rule to explicitly keep the classnames of the ComponentUI classes:

```
-keepnames class org.pushingpixels.substance.internal.ui.*
```

This pull-request removes the dynamicity of class lookups based on known names, instead relying on names resolved via `class.getName()`. Also it changes the `gradlew` shell script to be executable, as I couldn't run it when I cloned locally and therefore had to run `chmod +x ./gradlew`.

### CODE REVIEW

**Comment by kirill-grouchnikov** [comment]
I would suggest adding this to your proguard configuration instead:

```
-keep class * extends javax.swing.plaf.ComponentUI {
    public static javax.swing.plaf.ComponentUI createUI(javax.swing.JComponent);
}
```

This way you do not rely on the internal package name where the specific UI classes happen to be.

I am not quite comfortable with explicit class references in the proposed fix, by the way. This means loading classes that might not need to be there at all - for those apps that do not use specific Swing components like progress bars or sliders.

**Comment by michaelbull** [comment]
I already have that in my configuration for preserving the `createUI` function. However, the code I pasted above dynamically looks for classes in a specific package (`org.pushingpixels.substance.internal.ui`) for classes prefixed by `Substance` and suffixed with `UI`. The issue here is not that the `createUI` function is mangled obfuscated/removed, but moreso that we cannot rename these classes or repackage them because of the code that this PR changes.

**Comment by kirill-grouchnikov** [comment]
I'll need to think about this in the larger context of https://github.com/kirill-grouchnikov/radiance/issues/70 - specifically to see if there's any noticeable impact at startup time.

**Comment by kirill-grouchnikov** [comment]
The first part (using class references for UI delegates) has been submitted just now as part of the larger https://github.com/kirill-grouchnikov/radiance/commit/b4b692da074fed19ee72c1b39e29002c790105eb commit

Not sure about the access permissions on gradlew - I'm uploading files from my Windows machine and also building on a Mac laptop. Not seeing any issues running the script on both.

**Comment by michaelbull** [comment]
The `gradlew` shell script previously had 0644 as its permissions (you can see this on "Files changed" tab).
As you can see on [here](http://permissions-calculator.org/decode/0644/), 0644 does not permit executing as any group. I ran `chmod +x` on it, to allow myself to execute it, thus modifying the permissions to [0755](http://permissions-calculator.org/decode/0755/). No worries if you don't want to accept that change though, the other change is more important to me - thanks again.

**Comment by kirill-grouchnikov** [comment]
Doesn't look like GitHub's web interface allows merging only one change. Can you submit that one again separately so I can merge it?

**Comment by michaelbull** [comment]
#140

**Comment by kirill-grouchnikov** [comment]
Thanks!

**Pull request closed without merging**
