### PR TITLE
SvgBatchConverter: convert nested content

### LINKED ISSUE #251: [Photon / Ignite] Batch converter for nested content
Following the initial discussion at https://github.com/kirill-grouchnikov/radiance/pull/248

It is useful to provide support for transcoding SVG content to Java / Kotlin classes for more complex folder structure and not just one flat folder. For example, if the source folder has SVGs in nested subfolders, the output classes will match not just the source filenames, but will also be placed in the matching folder (sub)structure.

Instead of `sourceFolder` parameter, it will be `sourceRootFolder`. And instead of `outputPackageName` it will be `outputRootPackageName`. Then, starting from those roots, the destination folders will follow the source folder structure, and the package name for each transcoded class will be built from the root package name + the folder structure.

I'd like to not overcomplicate the existing `SvgBatchConverter` logic, but rather have it in a new `SvgBatchNestedConverter`.

### PR DESCRIPTION
**Pull request by simon04**
To address the complexity argument from https://github.com/kirill-grouchnikov/radiance/issues/251#issue-585770834, I've split the logic for the simple case (when `maxDepth==1`) and the sub-package case. Both code paths use the common function `convert()` to actually perform the transcoding.

Fixes #251.

### CODE REVIEW

**Comment by kirill-grouchnikov** [comment]
See https://github.com/kirill-grouchnikov/radiance/issues/251

I prefer this to be a separate converter class that uses a couple of different parameter names. In addition maxDepth is unnecessary mental overhead. You either convert one flat folder, or a whole nested structure.

**Comment by simon04** [comment]
The current `SvgBatchConverter` consists of 164 lines. This change introduces ≈32 additional lines. Do we really want a separate converter, separate `main()`, 164 duplicated lines when the feature is nicely wrapped in one function which gets executed conditionally?

**Comment by kirill-grouchnikov** [comment]
My priority is the long term health of everything that goes into the codebase. It's coming close to the 15th anniversary of when it started, and I'm looking at the next 15, hopefully. If I don't have the right mental model of the pieces, keeping things compartmentalized, that's not contributing to the codebase health.

I'm also not rushing to convert everything to use streams, optionals, etc just for the sake of newness. I'll make the first pass of addressing this functionality with implementation that is consistent with the rest of the codebase.

**Comment by simon04** [comment]
In 2011, I started contributing to @JOSM, which will also celebrate its 15th anniversary this fall. So I can relate to long-term decisions. :-)

Regarding the recursive transcoding, your positions seems rather unalterable – it boils down to having a separate converter which supports recursion, or no recursion at all?

**Comment by kirill-grouchnikov** [comment]
I will merge a CL later today that refactors `SvgBatchTranscoder` to extract the common pieces need for reusing, as well as reverting back to using `File` instead of `Path`.

Over the years the code base migrated through multiple source control systems, source code hosting, bug trackers etc. I'm taking the long view that contributors come and go (nothing personal), but the codebase stays in my head. Which is why I always prefer to start from discussing the proposed enhancements instead of fully-delivered pull requests.

**Pull request closed without merging**
