### PR TITLE
docs: wrap long command line for readability

### PR DESCRIPTION
**Pull request by simon04**

### CODE REVIEW

**Comment by simon04** [comment]
image

Err, the line is wrapped, but hard to read (where does the classpath end, where are the arguments, …).

**Comment by kirill-grouchnikov** [comment]
I don't see that https://github.com/kirill-grouchnikov/radiance/blob/b3b2917d4cf1a552ec3aa3842fb67fd9c4a5491a/docs/photon/photon.md is more readable, with a mix of two types of slashes. If there's a way to use bold to highlight the parameter names in that code block, I think that might be maybe more helpful.

**Comment by kirill-grouchnikov** [comment]
https://github.com/kirill-grouchnikov/radiance/blob/master/docs/photon/photon.md has been updated. Take a look and let me know what you think

**Comment by simon04** [comment]
Thanks for e44d6cb. Much more readable now :)

**Pull request closed without merging**
